# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - "*"
    exclude:
    - upstream/*


pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- script: make
  displayName: 'build challenge environment'

- script: docker run --rm challenge-env python3 -m pytest metrics/tests --dnsmos_uri $(dnsmosURI) --dnsmos_key $(dnsmosKey)
  displayName: 'Run test'

- script: docker image tag challenge-env:latest $(dockerRegistry)/challenge-env:latest
  displayName: 'Tag alphartc image'

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerRegistry: 'opennetlab Azure registry'
    repository: 'challenge-env'
    command: 'push'
    tags: 'latest'
  displayName: "Push challenge-env image"
